Vagrant::Config.run do |config|
  config.vm.box = "precise32"

  config.vm.forward_port 80, 8080
  config.vm.network :hostonly, "10.10.10.15"
  config.vm.share_folder("v-root", "/vagrant", ".", :nfs => true)

  config.vm.provision :chef_solo do |chef|
     chef.cookbooks_path = ["cookbooks", "site-cookbooks"]
     chef.add_recipe "apache2"
     chef.add_recipe "demo"
  end
end
